spring.application.name=finance
spring.datasource.url=jdbc:postgresql://localhost:5432/myfinance
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyImpl

spring.security.user.name=admin
spring.security.user.password=senha

jwt.secret= G15DELLJAVA21FINANCEDASH-VALENTINA-BITU-JOAO-VICTOR-BITU
jwt.expiration=3600000