ALTER TABLE accounts
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP;

ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP;

ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP;

ALTER TABLE refresh_tokens
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP;

ALTER TABLE cards
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP;

ALTER TABLE card_invoices
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP;

ALTER TABLE goals
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP;

ALTER TABLE recurrences
    ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP;
